### ISSUE TITLE
Lava Eel Crash

### ISSUE THREAD

**Issue by Voltage1243** [Chaos-Awakens-Mod-Team/ChaosAwakens#101]
Sometimes I punch a lava eel, I presume it tries to fight back since it goes into me. When this happens, the game immediately crashes without warning giving this message. I'm not sure if it is just me but this seems like something to look into.
(I accidentally closed the issue so this is a reupload.)
![image](https://github.com/ChaosAwakens/ChaosAwakens/assets/136834772/245107ac-a637-4907-a50d-b439699daf9f)

**Comment by Voltage1243** [comment]
I tried this in a small pool in the overworld and sometimes they don't attack and just stare at the wall. It may take more than one eel.

**Comment by RaveTr** [comment]
Known bug, fixed for next update. In the meantime, I suggest attempting to prune entities causing crashes out of your world using an editor (or using commands if you're on a server).
