### ISSUE TITLE
Wandering Trader Interaction Bug

### ISSUE THREAD

**Issue by Voltage1243** [Chaos-Awakens-Mod-Team/ChaosAwakens#103]
If you try to interact with a wandering trader while holding a CA weapon that increases reach distance, the wandering trader gets hit by the weapon held and basically dies. This does not apply to regular villagers since you cannot interact with them while holding a weapon.

**Comment by Voltage1243** [comment]
It also applies to armor stands so if you have a mod that gives armor stands arms then you can't place the weapons on the armor stand.

**Comment by RaveTr** [comment]
Already looked into, will potentially be tweaked for next update 👍
