### ISSUE TITLE
Invisible Extreme Torch

### ISSUE THREAD

**Issue by Voltage1243** [Chaos-Awakens-Mod-Team/ChaosAwakens#104]
I'm pretty sure this torch is supposed to not just be a floating fire particle.
![2023-08-06_00 26 23](https://github.com/ChaosAwakens/ChaosAwakens/assets/136834772/4e3288d8-1dde-4404-9ba2-9da00b590ed9)

**Comment by RaveTr** [comment]
Fixed for next update
