### ISSUE TITLE
Missing Texture Sign

### ISSUE THREAD

**Issue by Voltage1243** [Chaos-Awakens-Mod-Team/ChaosAwakens#105]
I added chaos additions, pure chaos, blackout's backpacks and spartan awakens. The CA signs are now missing textures. Not sure if this is a problem with this mod or the addons.
![2023-08-06_10 56 20](https://github.com/ChaosAwakens/ChaosAwakens/assets/136834772/0d35c264-1a27-4ebd-ba99-dec875381d35)

**Comment by RaveTr** [comment]
Likely the addons. Consult Blackout since he made those addons on his issue tracker for the respective mod(s). He is also a developer here, so he'll be able to help if it turns out to be an issue with CA.

**Comment by Voltage1243** [comment]
Does he have a github? Where can I talk about this with him?

**Comment by RaveTr** [comment]
Either on Discord, or his Github (you can find his profile in the list of contributors to this project).

**Comment by Voltage1243** [comment]
it fixed itself lmao
