### ISSUE TITLE
Chaos awakens morph mod crash

### ISSUE THREAD

**Issue by Natedogwoooof** [Chaos-Awakens-Mod-Team/ChaosAwakens#106]
i tryed to morph into an angry bunny from divine rpg i will try with a diffrent mod if u want me to
[crash-2023-08-11_11.47.52-server.txt](https://github.com/ChaosAwakens/ChaosAwakens/files/12323646/crash-2023-08-11_11.47.52-server.txt)

**Comment by Natedogwoooof** [comment]
https://github.com/iChun/Morph/issues/1250 also i reported it to morph mod github

**Comment by Natedogwoooof** [comment]
i think its becaaus eof the dragon armor

**Comment by RaveTr** [comment]
We aren't Divine RPG. Report it on their Github.

**Comment by Natedogwoooof** [comment]
> We aren't Divine RPG. Report it on their Github.

ok

**Comment by RaveTr** [comment]
Nevermind, just read the crash log lol

Fixed for next update, mod is being rewritten
