### ISSUE TITLE
lots of bug reports

### ISSUE THREAD

**Issue by RichConnerGMN** [Chaos-Awakens-Mod-Team/ChaosAwakens#107]
alright here we go, these are in no particular order. i'm aware that some of these are likely very difficult to fix.

- zoo cages and instant survival shelters can break bedrock
- corn will only grow up to 19 blocks unless you break the top block, in which case it'll just keep going until the next 19
- natural corn won't grow until block updated
- ent hurt and death sounds cut off early
- critter cages are used up in creative mode
- donkeys, llamas, mules, and trader llamas seemingly can't be put into critter cages (but horses can)
- wandering traders seemingly can't be put into critter cages (but villagers can)
- apple ents, cherry ents, peach ents, and skywood ents can be put into critter cages (but others can't)
- robo snipers can be put into critter cages (but the other robots can't)
- pigs, piglins, piglin brutes, and zombified piglins share the same critter cage texture
- skeletons, skeleton horses, and wither skeletons share the same critter cage texture
- horses and zombie horses share the same critter cage texture (presumably, since horses can't be captured, but the texture looks like a normal horse)
- apple cows, golden apple cows, enchanted golden apple cows, and crystal apple cows share the same critter cage texture
- the following mobs are missing critter cage textures: bat, blaze, chicken, cod, dolphin, elder guardian, endermite, evoker, ghast, guardian, hoglin, magma cube, ocelot, parrot, phantom, pillager, pufferfish, ravager, salmon, shulker, silverfish, squid, strider, tropical fish, turtle, vex, villager, vindicator, witch, zoglin, zombie, apple ent, cherry ent, peach ent, skywood ent, red ant, brown ant, rainbow ant, unstable ant, termite, tree frog, lettuce chicken, dimetrodon, emerald gator, crystal gator, ruby bug, stink bug, robo sniper, beaver, gazelle, carrot pig, golden carrot pig, enchanted golden carrot pig, whale, green fish, rock fish, spark fish, wood fish, lava eel, iron golem, snow golem, illusioner, giant (that took a while to type...)
- villager names in creature cages are their job title instead of "Villager" or "[Job] Villager"
- frozen polar bear, frozen snow golem, and frozen stray blocks have the stone breaking sound instead of the glass breaking sound	
- dimetrodon teeth and the things on their backs have z-fighting issues
- the mining dimension loads very..... very............... slowly....................................
- the rainbow ant and termite dimensions also load slowly, but not nearly as slowly
- crystal gator subtitles are labeled as emerald gator
- ent subtitles don't change depending on the ent even though the text is in the files
- hercules beetle wings have z-fighting issues
- the hercules beetle shake effect persists into the pause screen (also, the effect should be toggleable in accessibility settings, it kinda hurts my eyes a bit)
- instant survival shelter paintings are one block too far to the right when placed facing south or west and break off after a few seconds
- gate blocks cause some strange things when placing a block (especially other gate blocks) on them, or doing any other right click action on them (e.g. spawn egg)
- gate blocks sometimes don't disappear if you spam right click fast enough, especially when right in front of one (maybe due to timer being reset every time?) (also this really doesn't matter, you seemingly need to click exactly every 1 or 2 ticks)

**Comment by FunkyMonk16** [comment]
Lots of these bugs we know already and some of these bugs are just things we need to get to the redo like sound cutting off and z-fighting issues. But thanks for this.

**Comment by RichConnerGMN** [comment]
edited since the big update:

- zoo cages and instant survival shelters can break bedrock
- corn will only grow up to ~~19~~ 3 blocks (plus the top) unless you break the top block, in which case it'll just keep going until the next ~~19~~ 3
- natural corn won't grow until block updated
- ent  **walk,** ~~hurt, and death~~ sounds cut off early
- ~~critter cages are used up in creative mode~~ **partially fixed**
- donkeys, llamas, mules, and trader llamas seemingly can't be put into critter cages (but horses can)
- wandering traders seemingly can't be put into critter cages (but villagers can)
- ~~apple ents, cherry ents, peach ents, and skywood ents can be put into critter cages (but others can't)~~ **seems like none enter anymore**
- robo snipers can be put into critter cages (but the other robots can't)
- pigs, piglins, piglin brutes, and zombified piglins share the same critter cage texture
- skeletons, skeleton horses, and wither skeletons share the same critter cage texture
- horses and zombie horses share the same critter cage texture (presumably, since horses can't be captured, but the texture looks like a normal horse)
- apple cows, golden apple cows, enchanted golden apple cows, and crystal apple cows share the same critter cage texture
- the following mobs are missing critter cage textures: bat, blaze, chicken, cod, dolphin, elder guardian, endermite, evoker, ghast, guardian, hoglin, magma cube, ocelot, parrot, phantom, pillager, pufferfish, ravager, salmon, shulker, silverfish, squid, strider, tropical fish, turtle, vex, villager, vindicator, witch, zoglin, zombie, apple ent, cherry ent, peach ent, skywood ent, red ant, brown ant, rainbow ant, unstable ant, termite, tree frog, lettuce chicken, dimetrodon, emerald gator, crystal gator, ruby bug, stink bug, robo sniper, beaver, gazelle, carrot pig, golden carrot pig, enchanted golden carrot pig, whale, green fish, rock fish, spark fish, wood fish, lava eel, iron golem, snow golem, illusioner, giant (that took a while to type...)
- ~~villager names in creature cages are their job title instead of "Villager" or "[Job] Villager"~~ fixed
- ~~frozen polar bear, frozen snow golem, and frozen stray blocks have the stone breaking sound instead of the glass breaking sound~~ **fixed**
- dimetrodon teeth and the things on their backs have z-fighting issues
- ~~the mining dimension loads very..... very............... slowly....................................~~ **mostly fixed**
- t~~he rainbow ant and termite dimensions also load slowly, but not nearly as slowly~~ **fixed**
- crystal gator subtitles are labeled as emerald gator
- ent subtitles don't change depending on the ent even though the text is in the files
- ~~hercules beetle wings have z-fighting issues~~ **fixed by redesign**
- ~~the hercules beetle shake effect persists into the pause screen (also, the effect should be toggleable in accessibility settings, it kinda hurts my eyes a bit)~~ **fixed (but still no toggle)**
- instant survival shelter paintings are one block too far to the right when placed facing south or west and break off after a few seconds
- gate blocks cause some strange things when placing a block (especially other gate blocks) on them, or doing any other right click action on them (e.g. spawn egg)
- gate blocks sometimes don't disappear if you spam right click fast enough, especially when right in front of one (maybe due to timer being reset every time?) (also this really doesn't matter, you seemingly need to click exactly every 1 or 2 ticks)

**Comment by RaveTr** [comment]
- Critter cage has a size constraint now.
- Critter cage textures in general will be redone.
- Subtitles and sounds will also be redone/organized.
- There is a toggle in the client config for screen shake.
- Instant structure blocks will be undergoing a rework.
- Dimetrodons and entities in general are susceptible to getting reworked, dw.
- Will look into Gate Blocks/Crops for upcoming patch update.

Thanks for the bug report. Will mark as closed upon dropping the patch.

**Comment by RichConnerGMN** [comment]
thank you! i think it should be moved to the accessibility and video settings screens, but having the option there at all is nice.
as for the gate blocks, i think the problem is that you can place blocks on them while they're in the transition state between being right clicked and disappearing, and newly placed gate blocks can also disappear from being next to existing ones. i think the best solution would be to make it so you when you're holding a gate block, you can't activate other gate blocks.

**Comment by RaveTr** [comment]
Mod receiving a rewrite next major update (for porting, duh reader!!!). All of the addressed issues have been patched.
