### ISSUE TITLE
Whale causing crash on server [1.16.5]

### ISSUE THREAD

**Issue by Sirbester** [Chaos-Awakens-Mod-Team/ChaosAwakens#109]
[crash-2024-01-01_18.54.52-server.txt](https://github.com/ChaosAwakens/ChaosAwakens/files/13806364/crash-2024-01-01_18.54.52-server.txt)

**Comment by RyderWanted** [comment]
same happened to my friend, whale entity causing a crash on the singleplayer world, he's losing connection to his own world bro

**Comment by RaveTr** [comment]
Next update (0.12.0.0) is a rewrite of the entire mod (look forward to it :)), so until then, I'd recommend disabling whale spawns via a 3rd party mod.

**Comment by RaveTr** [comment]
Fixed in 0.12.
