### ISSUE TITLE
Too many dimetrodons in the mining dimension.

### ISSUE THREAD

**Issue by Mcflame1539** [Chaos-Awakens-Mod-Team/ChaosAwakens#118]
I have noticed that the mod spawns a ton of dimetrodons in the red ant dimension AKA the mining dimension. To attempt to keep TPS somewhat high in that dimension. I had to create a bedrock room that has a hopper timer connected to a command block that kills all the dimetrodons every few minutes. I believe if you severely limit how often the game spawns them. And how many they spawn. It should raise the TPS of the dimension.

**Comment by RaveTr** [comment]
Fixed in 0.12.
