### ISSUE TITLE
Uses different GeckoLib version than Mowzies Mobs and Ars Noveau (and other mods with the updated GeckoLib version)

### ISSUE THREAD

**Issue by Boiber** [Chaos-Awakens-Mod-Team/ChaosAwakens#128]
The latest version of Chaos Awakens uses an outdated version of GeckoLib, which makes it incompatible with certain mods that do use the latest version, like Mowzie's Mobs.

**Comment by RaveTr** [comment]
The solution would be to use older versions of both of the other mods.

GeckoLib3 just straight up breaks for us in newer versions. We remade entire entities several times, looked through changelogs.. it's not worth patching a GLib3 bug from our end when we're already porting.

If we do coincidentally find a solution during our patch phase, though, we will be incorporating it into 0.12.0.1.

**Comment by Poopooracoocoo** [comment]
Just for convenience, the following versions work:

Mowzie's Mobs 1.5.25 
https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/3788735

Ars Nouveau 1.25.8
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/4054248

GeckoLib 3.0.96
https://www.curseforge.com/minecraft/mc-mods/geckolib/files/4031255

<img width="218" height="141" alt="Image" src="https://github.com/user-attachments/assets/935d3802-c14a-4dbe-8f6a-440cb9ca3161" />
