### ISSUE TITLE
Console log spam from server attempting to fetch models that don't exist on the server-side

### ISSUE THREAD

**Issue by Moecchiato** [Chaos-Awakens-Mod-Team/ChaosAwakens#136]
When playing multiplayer the console will get spammed with this message constantly and gets worse as more entities get loaded. Happens with multiple entities than just the lettuce chicken.

![Console Spam](https://github.com/user-attachments/assets/d0b9388d-d27f-4b71-8d96-8f0faceeefc5)

**Comment by uncertainluei** [comment]
A weird GeckoLib issue where it tries fetching models from the server while they don't exist. We recommend ignoring it for the time being, but a fix should come if any further patch release to v0.12 happens

**Comment by uncertainluei** [comment]
Fixed in v0.12.0.2
