### ISSUE TITLE
Division by Zero on Burn effect

### ISSUE THREAD

**Issue by Dockuin** [Chaos-Awakens-Mod-Team/ChaosAwakens#137]
I was playing on a minecraft server when I was fighting a skeleton. I got hit by and arrow and attacked it and I was forced off the server with the message "java.io.ioexception an existing connection was forcibly closed".
I went into the console log and realised that the actual crashlog for my account read something about an "arithmetic issue: / by Zero at io.github.chaosawakens.potion.BurnEffect" or something like that.

I was luckily able to fix the issue by removing the Burn Effect from my ActiveEffects in my playerdata file but it while it was happening, it was crashing me every time I tried to rejoin.

**Comment by Noah1210** [comment]
Happened to me too just now, but they might already have uploaded a fix for this bug since I'm reading in the recent commits "Fix for possible arithmetic error" and when launching my server it warns me that there's a new version for ChaosAwakens available

**Comment by RaveTr** [comment]
Fixed in 0.12.1.0.
