### ISSUE TITLE
Many mobs with z fighting issues i'm pretty sure

### ISSUE THREAD

**Issue by Dashy22** [Chaos-Awakens-Mod-Team/ChaosAwakens#138]
just spawn any type of gator to see a personal disco on their 2 buck teeth
the crystal gater crystals also have the bad disco shading
The birds have the disco feet.
All carrot pig types have a singular singularity on their frontmost carrot.
Dimetrodan has the same disco deer teeth as the gators.
Green Fish and Wood Fish both have flashy top and back fins.
Rock Fish with the strobe lights fused with his flippers.
Spark Fish is having some crazy club on all their fins and flippers.

Robo warrior has something different going on with pink edges on the invisible squares/texture space, with the floating crystals around his head.

I'm pretty sure I checked most mobs.

**Comment by RaveTr** [comment]
Not game-breaking. We will be updating assets as we move onwards from 0.13.x.x+.
