### ISSUE TITLE
When lagging the Robos take a long time to drop loot

### ISSUE THREAD

**Issue by Moecchiato** [Chaos-Awakens-Mod-Team/ChaosAwakens#142]
Like the title said, all the robos take a long time dropping loot when there is lots of lag.

![2024-08-24_02 48 19](https://github.com/user-attachments/assets/74879e16-3d15-4f56-a700-7fa2bc203a8e)

**Comment by RaveTr** [comment]
Makes sense. Lag means that some ticks get skipped. As such, it takes longer for server-side animation progress to catch up and sync.

That being said, FAAL (the backend API built into CA, and on top of GeckoLib) will be rewritten to adopt an event-queue handler-type system to effectively eliminate/mitigate the effects of lag on animations in 0.13.0.0.
