### ISSUE TITLE
Brown Ants Dimention isn't working please healp me :(

### ISSUE THREAD

**Issue by BlueFish1926** [Chaos-Awakens-Mod-Team/ChaosAwakens#150]
Pls help the brown ant dimention isnt working, it keeps giving me the message "Dimention isn't added to the mods" eventhough i have check the log and its still have the brown ants dimention settings, if anyone know how to fix it pls help me, im using Chaos Awaken 1.16.5-0.12.1.1 for crazy craft and i dont know how to fix it  :(

**Comment by PhweeDev** [comment]
If the mod said it isn't added. it's not added. It'll be added in the future when we're ready for it.
