### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Yonk316** [Chaos-Awakens-Mod-Team/ChaosAwakens#18]
[crash-2021-06-07_13.04.52-fml.txt](https://github.com/Chaos-Awakens-Mod-Team/ChaosAwakens/files/6610852/crash-2021-06-07_13.04.52-fml.txt)
![Screenshot (7)](https://user-images.githubusercontent.com/42360206/121061367-9c775000-c778-11eb-9f5c-67ae8fe38b40.png)

**Comment by Yonk316** [comment]
Suspect its a issue with GeckoLib

**Comment by jtrent238** [comment]
> Suspect its a issue with GeckoLib

Yes it is

**Comment by invalid2** [comment]
Yes, Geckolib is a required dependency

**Comment by invalid2** [comment]
> Forge 1.16.5 - 36.1.13 or higher is required.
> Geckolib geckolib-forge-1.16.5-3.0.31.jar is required.
