### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by Yonk316** [Chaos-Awakens-Mod-Team/ChaosAwakens#29]
[crash-2021-10-03_08.26.54-fml.txt](https://github.com/ChaosAwakens/ChaosAwakens/files/7273319/crash-2021-10-03_08.26.54-fml.txt)

**Comment by Blackout03** [comment]
Fixed in like 5 minutes, uploading fixed version to website now

**Comment by Blackout03** [comment]
Said version is now released! Have fun!
