### ISSUE TITLE
Changing attack damage values in config doesn't change them in-game

### ISSUE THREAD

**Issue by natkos21** [Chaos-Awakens-Mod-Team/ChaosAwakens#48]
After I changed the attack values, the in-game value stays the same as before.
![Screenshot (5)](https://user-images.githubusercontent.com/95502402/145386433-79257501-15ef-4a6e-8a28-3c8663d7280c.png)

**Comment by invalid2** [comment]
Could you attach a log, please?

**Comment by natkos21** [comment]
[latest.log](https://github.com/ChaosAwakens/ChaosAwakens/files/7687331/latest.log)

**Comment by RaveTr** [comment]
> [latest.log](https://github.com/ChaosAwakens/ChaosAwakens/files/7687331/latest.log)

did you relaunch the game afterwards? It may seem obvious but the log has nothing weird going on afaik

**Comment by natkos21** [comment]
Of course. In fact, I always quit the game before changing something in configs because I'm afraid I'll break something. I also created a new world, just in case the value *somehow* was saved in my test world. And there was no change.

**Comment by RaveTr** [comment]
hmm, weird. Will look into it and update you further, probably in like 4-ish days. Thanks for bringing this issue to light

**Comment by natkos21** [comment]
Alright.

**Comment by RaveTr** [comment]
Note: Should be fixed by patch 0.11.0.2
