### ISSUE TITLE
[question] will the mod be taken down soon?

### ISSUE THREAD

**Issue by Brandonbr1** [Chaos-Awakens-Mod-Team/ChaosAwakens#52]
if you go to [https://www.orespawn.com/download/](https://www.orespawn.com/download/) it says no port of the mod

![dmca](https://user-images.githubusercontent.com/74426342/148229142-fac48112-4039-407c-9ede-e9c0dd6180ab.PNG)

**Comment by RaveTr** [comment]
No. We have taken pretty much no assets from the original mod, and have remastered most of the stuff in CA. We complied with danger's guidelines as to what can and can't be used, and he has made it clear at that time that he has no problem with the mod itself. For now, just ignore this until further notice

**Comment by Blackout03** [comment]
> No. We have taken pretty much no assets from the original mod, and have remastered most of the stuff in CA.

We have taken NO assets from the original mod.

**Comment by Blackout03** [comment]
Also this is not what issues are for Brandon.
