### ISSUE TITLE
Corn Overgrowth Crash

### ISSUE THREAD

**Issue by keepinitreal247** [Chaos-Awakens-Mod-Team/ChaosAwakens#59]
So I have mystic tools installed alongside this mod and the tools can have a special effect called "Growth aura" which basically causes the rapid growth of plants and crops around the player. So it seems that this "effect" causes any corn crop from this mod to reach its "Growth" limit which in turn causes a crash. This is just speculation and I could be wrong but here's the crash log 

[https://gist.github.com/keepinitreal247/3222613c569f7eeb4fc404d2bca6f0f7](url)

P.S.-It also seems like the ants and termites still spawn wayyyy too much I haven't really seen anyone else mention it but I just happen to notice that if I don't break an ant/termite nest they just keep spawning.

**Comment by RaveTr** [comment]
I've already fixed this issue, it will be pushed out by the next update.

For now, you should just avoid using anything that accelerates crop growth with CA plants until the next update has been released.

And as for the ants, unless you have beta access there is no fix yet. Yeah, lots of stuff will hopefully be resolved by next update.
