### ISSUE TITLE
Ants spawning in uncontrollable Quantities. 

### ISSUE THREAD

**Issue by Moomsy** [Chaos-Awakens-Mod-Team/ChaosAwakens#66]
So i am running a private Modpack and after a fresh start we added ChaosAwakens to the Pack. Now everything is just amazing gotta state that , BUT heres the twist - even the ones of us that have amazing Power in their Pc's experience lag since the Ants just break out of control. i dont know if its possible to limit the amount and if not is there a r5ecommendation to a tool/mod that could deal with it ? in the meantime we just reak all Nests we can find and kill the Ants.

Also small thing : is it normal that Ants drop Ancient Debris and Shulker boxes ? :D

**Comment by Blackout03** [comment]
The many ants spawning was fixed in the April fools update (0.9.0.4) and will of course be fixed in the next major update as well.

Ants should not drop ancient debris or Shiller boxes. You mush have a random drops mod installed or something.

**Comment by Moomsy** [comment]
Awesome Thanks for clarifiying! I am using Incontrol and SBU for the Time beeing to handle it temporarily.


I took a look and i first thought it was because of Enigmatic Legacy's Ring of Curses but removing the mod and killing Ants still drops Ancient Debris and Shulkers at a Rate of 0.5-1% sometimes. Maybe something ive overlooked but funny nonetheless. Also i noticed that JustEnoughResource sometimes does not show drops even when Integr Mode is enabled but thats probaly something on JERs End.
