### ISSUE TITLE
[Suggestion] License all mod code under GPL, and license all assets under CC BY-NC-SA 4.0

### ISSUE THREAD

**Issue by MoleMad** [Chaos-Awakens-Mod-Team/ChaosAwakens#71]
https://www.gnu.org/licenses/gpl-3.0.html
https://creativecommons.org/licenses/by-nc-sa/4.0/

I'm aware it's a bit discourteous for me to tell you how to license your own code and assets, but considering what happened to orespawn itself, I think it's reasonable to have reservations about mods that are "all rights reserved." In my experience, Free Software and Creative Commons licenses are what allow the modding community to flourish and have much greater longevity, while also ensuring that all third party contributions are free for everyone to use and modify as well. Please consider this option for the future.

**Comment by RaveTr** [comment]
As long as this mod is incomplete, the licensing will stay the same. This decision can be overridden at any given time.
