### ISSUE TITLE
Fall damage is bugged 

### ISSUE THREAD

**Issue by RogueZombieDog** [Chaos-Awakens-Mod-Team/ChaosAwakens#75]
Fall damage is like you are not wearing any armour when wearing the queen scale armour (havent tried the others)

**Comment by RogueZombieDog** [comment]
actually it seems like no protection is given at all with a zombie killing me easy

**Comment by RaveTr** [comment]
Myself and several other developers have tried replicating the issue, to no avail. All I can suggest is reinstalling the mod, or if you have other mods downloaded, to check for any conflicts going on
