### ISSUE TITLE
Mining paradise lags

### ISSUE THREAD

**Issue by Rumaruka** [Chaos-Awakens-Mod-Team/ChaosAwakens#79]
Hello, I'm trying to teleport to dimension Mining paradise, but the world doesn`t generate correctly, very much reduces tps

**Comment by RaveTr** [comment]
Known issue. Disable ore generation on Stalagmites through the common config. Fixed for next update.

**Comment by Rumaruka** [comment]
Oh, thank you for information <3
I'm close issue
