### ISSUE TITLE
Zombie Pickup Crash

### ISSUE THREAD

**Issue by crzyc** [Chaos-Awakens-Mod-Team/ChaosAwakens#81]
When a Zombie picks up a Royal Guardian Sword / Queen's Battle Axe (probably can replicate with Big Bertha, though I haven't tested it) and attacks the player, the game crashes. 

[Crash Log](https://pastebin.com/e6Yyrzce)

**Comment by RaveTr** [comment]
Known issue with any extended weapons in general. Fixed for next update.
