### ISSUE TITLE
Random ban from chaos awakens discord

### ISSUE THREAD

**Issue by PhilCrafter** [Chaos-Awakens-Mod-Team/ChaosAwakens#82]
Sorry to bug you guys here but tonight I was banned from the ChaosAwakens Disocrd and I don't know where else to complain.
The ban massage:
![image](https://user-images.githubusercontent.com/24317708/220081930-fec626ca-63a7-499d-a152-056b46418e74.png)

I can provide my username if necessary, but I would prefer not just putting it in a public ticket.

**Comment by RaveTr** [comment]
Not a mod issue. You know what you did.

**Comment by PhilCrafter** [comment]
I don't understand? I never even said anything on the discord. So wtf did I do?

**Comment by RaveTr** [comment]
You joined multiple servers simultaneously, were unverified until recently on many of them when you suddenly became active. Your account has the generic IRL name. This server isnt the only one you were banned from.

In short, you're suspected alongside a couple others of being an alt account. You know who you are.

Dont comment on this github unless it is a mod issue. If you can prove the allegations false, you will be unbanned. These are precautionary measures taken based on past experience.

This topic is closed and you will no longer be replied to on here.

**Comment by KingOfTheGamesYT** [comment]
They do this, they randomly ban people for no reason. I'm Kat and they think you are my alt even though we have no relation to each other
