### ISSUE TITLE
Ban from discord still no explaination 

### ISSUE THREAD

**Issue by PhilCrafter** [Chaos-Awakens-Mod-Team/ChaosAwakens#83]
The old ticket was closed with no help or explaination given to me.
![image](https://user-images.githubusercontent.com/24317708/223992703-ffb04e39-c59c-48ec-b684-6e0487edc03a.png)
What is it that I have done wrong to get banned? I dont want to create a new discord account just for chaos awakens.

**Comment by RaveTr** [comment]
Tickets unrelating to problems with the mod itself will be closed with no exceptions. It says your ban reason right there. Please do not spam the Github issues page with topics that clearly aren't mod issues.
