### ISSUE TITLE
Compatibility issue with ExpandAbility Mod

### ISSUE THREAD

**Issue by Mystrik** [Chaos-Awakens-Mod-Team/ChaosAwakens#84]
Probably already a known issue, but wanted to have the issue posted somewhere (I'm a big fan of the artifacts mod).
Game crashes on startup with the ExpandAbility Mod, which seems to be a library mod for the Artifacts mod. Disabling ExpandAbility and Artifacts fixes the crash.

Mod Versions:
chaosawakens-1.16.5-0.11.0.1.jar
expandability-2.0.1-forge.jar
Artifacts-1.16.5-2.10.5.jar

**Comment by Blackout03** [comment]
Known issue, fixed for next version. Thank you for the report anyway. If you find any other issues feel free to report them.
