### ISSUE TITLE
Incompatibility with Rubidium 

### ISSUE THREAD

**Issue by Linksapprentice** [Chaos-Awakens-Mod-Team/ChaosAwakens#85]
I was running a slightly changed version of ragnamod 6 which natively includes rubidium. Upon world startup or joining a server with the same mod list the game would immediately crash. I switched to roadrunner and the game ran fine. I’ve now verified that the mod that was causing this incompatibility was Chaos Awakens. The exact error I was getting seemed to be caused by a script left hanging by the mod. I’m afk but I’ll update this report with the exact error description later.

**Comment by Blackout03** [comment]
Ragnamod VI doesn't have Chaos Awakens unless the slightly changed version adds it or you added it, but also Chaos Awakens works fine with Rubidium.

**Comment by FunkyMonk16** [comment]
You got the crash report yet?
