### ISSUE TITLE
Question regarding your mod

### ISSUE THREAD

**Issue by DKLYNTLY** [Chaos-Awakens-Mod-Team/ChaosAwakens#86]
Ik people have asked you this question many times, however, I need to know since I am a modpack creator. When is the next update? I need to update my modpack

**Comment by PhweeDev** [comment]
If you checked the Discord and CurseForge page, it says the following:

"Q. When is the next update?

A. There are no ETAs (estimated time of arrival) for updates. Mod updates will be released when they are ready."

Simply, they are no ETAs given. you'll have to wait until an update is released.
