### ISSUE TITLE
[1.16.5] Crash in nether

### ISSUE THREAD

**Issue by Rumaruka** [Chaos-Awakens-Mod-Team/ChaosAwakens#87]
Hello, after teleport to dimension
I have crash - 
[crash-2023-03-21_14_30_11-server.txt](https://github.com/ChaosAwakens/ChaosAwakens/files/11027824/crash-2023-03-21_14_30_11-server.txt)

**Comment by FunkyMonk16** [comment]
Thank you, we will look into it.

**Comment by RaveTr** [comment]
Fixed for next update, entity code has been refactored. Lava creatures from CA won't be causing issues by next update 👍
