### ISSUE TITLE
Crashing with dedicated server. (net/minecraft/client/gui/widget/Widget)

### ISSUE THREAD

**Issue by Stried** [Chaos-Awakens-Mod-Team/ChaosAwakens#89]
[crash-2023-04-03_13.13.36-fml.txt](https://github.com/ChaosAwakens/ChaosAwakens/files/11134990/crash-2023-04-03_13.13.36-fml.txt)

There are no other mods other than Chaos Awakens

**Comment by Blackout03** [comment]
Fixed this is a patch update for the April Fools Update.
Check out 0.11.1.1.

Now people can run servers on the April Fools version.
