### ISSUE TITLE
Dedicated server closing

### ISSUE THREAD

**Issue by Kilercarno** [Chaos-Awakens-Mod-Team/ChaosAwakens#91]
Hi.
I've been running a dedicated server for a few of my friends and I to play on, and after updating to the latest version (0.11.1.1), the server no longer starts. There is no crash log, but I attached the latest server log. 
[latest.log](https://github.com/ChaosAwakens/ChaosAwakens/files/11165656/latest.log)

**Comment by FunkyMonk16** [comment]
The newest CA update is the April Fool's one. We are currently working on a patch.
