### ISSUE TITLE
Fish spawning out of water

### ISSUE THREAD

**Issue by tas367** [Chaos-Awakens-Mod-Team/ChaosAwakens#92]
I apologize if this is already a known issue, im experiencing a bug where fish will randomly spawn out of water and sometimes high up in the air
modpack: crazy craft (updated) 
mod version: 0.10.0.2
java version: 1.8.0_362
OS: linux
launcher (not sure if applicable): multimc

steps to reproduce:
1. generate world 
2. wait a few min-hours and bug should occur.

**Comment by tas367** [comment]
Additional info:
light level seems to potentially play a role 
screenshots:
![2023-04-09_23 03 17](https://user-images.githubusercontent.com/97321139/230837624-e86104b9-d59a-42f0-af46-6c3ed9205a1d.png)
![2023-04-09_22 55 05](https://user-images.githubusercontent.com/97321139/230837668-16b4c7f9-6591-4d64-9419-3ebb981b51bc.png)
![2023-04-09_22 58 37](https://user-images.githubusercontent.com/97321139/230837685-219921d3-7965-4585-b8b2-7c651e55b92f.png)

**Comment by FunkyMonk16** [comment]
You are playing on an old version of Chaos Awakens. You need to be on a newer one. 
The newest being 0.11.0.1.
