### ISSUE TITLE
mobs are big and tiny

### ISSUE THREAD

**Issue by kardask67** [Chaos-Awakens-Mod-Team/ChaosAwakens#94]
![2023-05-17_17 57 55](https://github.com/ChaosAwakens/ChaosAwakens/assets/108549039/321ca5d0-fb2a-458f-a405-bf6bc5b9c214)
![2023-05-17_17 58 23](https://github.com/ChaosAwakens/ChaosAwakens/assets/108549039/1a5d2018-42dd-4135-8236-826db871d9bc)

**Comment by PhweeDev** [comment]
You're playing the April Fool's version. Download 0.11.0.1 instead.

**Comment by Blackout03** [comment]
You are playing on the April Fools version of the mod

**Comment by Blackout03** [comment]
I am too slow
