### ISSUE TITLE
clash

### ISSUE THREAD

**Issue by ghost** [Chaos-Awakens-Mod-Team/ChaosAwakens#95]
https://github.com/florensie/ExpandAbility/issues/7

**Comment by ghost** [comment]
It is also hoped that the official version of ChaosAwakens will use Java11.

**Comment by ghost** [comment]
chaosawakens-1.16.5-0.11.1.2.jar also conflicts with ExpandAbility

**Comment by RaveTr** [comment]
Known issue, fixed for next update (codebase refactor/rewrite). Also, 1.16 only supports Java 8, and versions above support Java 17+, so no, no Java 11 support.

**Comment by ghost** [comment]
Since other mods require Java11, this has some impact on modpack. Hope to support Java11.

**Comment by RaveTr** [comment]
Which mods require Java 11?? Most mods do not. 
Again, we will not be supporting Java 11 in the foreseeable future.

**Comment by ghost** [comment]
Modern UI   This mod is very good and I don't want to give it up, but I would give up the Modern UI if it was too much trouble to modify.

**Comment by ghost** [comment]
But strangely enough, version 0.11.1.2 can be booted with Java11.

**Comment by RaveTr** [comment]
It is up to you to choose which mods you would like to drop. We aim to try and be compatible with most mods, but mods that use different Java versions for whatever reason aren't worth the effort to debug and add special compatibility with.

Your original question has been answered. A refactor update will be coming out soon, which should solve most if not all compatibility issues with CA.
