### ISSUE TITLE
Lava Eel Armor in Creative Bug

### ISSUE THREAD

**Issue by Voltage1243** [Chaos-Awakens-Mod-Team/ChaosAwakens#99]
if you activate creative flight while swimming in lava, you are stuck in swim/crawl position and cannot sprint in the air or on the ground, double space in lava to fix like how you would to activate creative flight

**Comment by Voltage1243** [comment]
![2023-06-16_08 44 45](https://github.com/ChaosAwakens/ChaosAwakens/assets/136834772/aa2e26e5-2f4d-4c59-95b1-93d22fc61142)

**Comment by RaveTr** [comment]
Already reported, fixed for next update
